### ISSUE TITLE
关于相机内参和外参的问题

### ISSUE THREAD

**Issue by Olivialyt** [zzc-1998/MM-PCQA#1]
您好，请问您在处理SJTU-PCQA数据集时，将三维点云投影成二维图片的过程中，所使用的相机内参和外参矩阵方便告知一下吗？谢谢！

**Comment by zzc-1998** [comment]
你好，可以在这个文件内 https://github.com/zzc-1998/MM-PCQA/blob/main/utils/get_projections.py
利用o3d将crtl转化为相机的内参和外参矩阵，具体可以参照open3d的文档
