### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rotate' 

### ISSUE THREAD

**Issue by jukieCheung** [zzc-1998/MM-PCQA#4]
Hi, sorry for disturbance.
When I tried to use your test code to test my own data. I cannot run properly.
Here is the following problem:

Traceback (most recent call last):
  File "test_file.py", line 139, in <module>
    main(config)
  File "test_file.py", line 124, in main
    process_file(ply_file, config.ckpt_path, model, results)
  File "test_file.py", line 84, in process_file
    imgs = ply2projections(ply_file)
  File "test_file.py", line 70, in ply2projections
    ctrl.rotate(rotate_para[i][0], rotate_para[i][1])
AttributeError: 'NoneType' object has no attribute 'rotate'

**Comment by zzc-1998** [comment]
Hello,
This error seems to indicate that you haven't successfully loaded the point cloud file, therefore the ply object is 'NoneType'.
Check your ply file path and format, and visualize before processing to see whether the point cloud is loaded correctly.

**Comment by MichaelWangGo** [comment]
@jukieCheung I got the same error, but the key problem was that I ran the code in an env without visulization. I changed to another env with visulization, then it works.
